### ISSUE TITLE
heatmap layer visible property does not work properly.

### ISSUE THREAD

**Issue by altamf** [opengeos/leafmap#656]
I have added a heatmap to the map using `add_heatmap` and it functions properly. However, when I try to set `visible=False/True`, it does not have any effect and the layer will always be visible. I have also tried the `LayerControl ` menu and that did not work either. 

For other layers, both the layer control and the `visible `property works fine.

### Environment Information

-   leafmap version: '0.29.1'
-   Python version: 3.8.18
-   Operating System: Windows 11

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
This is an issue with ipyleaflet rather than leafmap. The problem is that the ipyleaflet Heatmap class does not implement the `visible` attribute. Therefore, the leafmap custom toolbar won't be able to change the visibility of the layer. However, you can still use the ipyleaflet builit-in toolbar to toggle layer on/off. You can [open](https://github.com/jupyter-widgets/ipyleaflet/issues) an issue on the ipyleaflet repo about the missing `visible` attribute. There is not much leafmap can do about this unless ipyleaflet supports it. 

https://ipyleaflet.readthedocs.io/en/latest/layers/heatmap.html

```python
from ipyleaflet import Map, Heatmap, LayersControl
from random import uniform
m = Map(center=(0, 0), zoom=2)

heatmap = Heatmap(
    locations=[[uniform(-80, 80), uniform(-180, 180), uniform(0, 1000)] for i in range(1000)],
    radius=20
)

m.add(heatmap)
m.add_control(LayersControl())

m
```
