### ISSUE TITLE
Pinning dependencies?

### ISSUE THREAD

**Issue by rbavery** [opengeos/leafmap#685]
### Description

Are the maintainers open to a PR pinning dependencies to latest python versions? And installing something like [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) for keeping dependencies up to date? 

This would allow users of the library to rely on specific versions of leafmap installing specific versions of it's dependencies to improve interoperability in their environments.

If this sounds good I can pip freeze and only specify the top level dependencies that are currently specified, updating the requirements.txts and do the same for the environment.yaml.

**Comment by giswqs** [comment]
Good suggestion. PR is welcome.

**Comment by maartenbreddels** [comment]
Hi,

This makes installing leafmap in pyodide or pycafe very difficult, since they have some version constraints.
If possible, I think libraries should not do this, as it makes installing alongside other libraries problematic.

[Example link](https://py.cafe/snippet/solara/v1#c=H4sIAIX8JGcAA61UbW_bNhD-KwL3JQMkxbIlOxXgDduQYcVWYCiGFYNpGLR0trnRJEfSblXD_71H0XL9kjRpUAMJxLuHzz28tx2pVA2kJHytlXGRALZYM53in-BzA0sRMdtZqTygdFOxBVBJ5XfRm5_-_Ov1H_dvZ7_f_xONjwRLcDOm-ew_aG4oOQVR8j2VF7cCYXvJQmXAPXRnfUL_hukbKiP8VSAdmPEkGeVprzccxlHeS0fZoJjG0Uel1uMMTZq7ajXOiziaAzNcLsdJNooj6xoBY0rmzPIq2fYpodIHSlldz9AIGAqV3FvD03fKiPr1mi3BNJTE0ZZbPsfbvzJhAS9ZtTEVoMRd0EXJxghKymhByco5bcvbW0yIz6zjAkxaqfWt_7K320H4SP-1Sv6IGRvvTh-_x3Adp2s0eFJKtlA5ZVrX3ldCsAbMaXheB-CgTuYbLmp8tT1hCnoDRGmQB13XkKRlDsCO6EFFCy5EAh-c2Viu5AlkzWXiS-FhWXE0a8al87aD5GA9Z0kqJfwry2jyGXR4n6-7VoI5jH8g7X4TSgSXWGpKptcubDNfQUoMyBrMbAV8uULTJbR3cfakCFwa5jvg3NfvXaONapiYi821vvwBdMt9hT7VdJWcTvg3zU6o1KXjWLfHkoNj9qJEf_GBfgYffF7VOq4j_oDTHJ-F7p6DAp_RCtiqz2qHzrcP4xc2RpgXXBgX8xQFx3GztAN10_4_t80qJZ1R4sabSYyi_t9wA2tccRZ3tMVyGoajHpbgpFvS0_G4lw7u0qxPpWayZpbKJajus4P5LYGkfmCPZHhmWv_N4T0pF36TxQRq7u4lw91GSqwDWnTjVkriHd2omteQbHtpf5j28TLKVhtHyh3uI-NLRso-6lbKvVVIueuiGTzFpFrh-sBMk3Jy9Dg2t-DQ-Z7XbkXKrOjFfmO8C8dBOP3W1iQceY3XsFHgZ2S1YH7BpOEqAfNIBA9N5gGLEM08LyH76T7-Kn0HCV7fI8DP7JjUVDfnMV7GdNoDqfvgPOcLlWd5nuaDUTG4u8txA_WL5yT6kLinktzl94kXF2kx7OfDLCuKV69GRRaTMG2kzPPRc-TgVkMzE0_p6XAhXdP9Pm77AMdoMt1_Aubwfyn2CAAA)

Regards,

Maarten

**Comment by giswqs** [comment]
@maartenbreddels Thank you for reporting. Should we remove version pin for xyzservices only or all dependencies?

**Comment by maartenbreddels** [comment]
I would recommend removing all, unless they are really needed because of a feature missing.

**Comment by giswqs** [comment]
@maartenbreddels I just released a new version without dependency version pins.

**Comment by maartenbreddels** [comment]
awesome, a transitive dependency depends on `setuptools>=70.0.0`, which is the next blocker. Any idea what that can be?

**Comment by giswqs** [comment]
I forgot why setuptools is listed there. Anyway, I just removed it and released a new version.

**Comment by maartenbreddels** [comment]
Alright, this is a super good stress test!

https://py.cafe/maartenbreddels/leafmap-maplibre-test

It installs now 🥳 , but it crashes on chrome, due to memory use (we can improve that probably).
Firefox and Safari do not display the widget, which is odd.

Anyway, thanks for helping me out, we have some work to do, but it seems like a lot of obstacles are removed!

**Comment by giswqs** [comment]
maplibre has some large dependencies that may be challenging to install on py.cafe. That's one of the reasons I haven't added maplibre as a required dependency.

**Comment by rbavery** [comment]
@maartenbreddels @giswqs just a heads up that I brought up this request because leafmap with unpinned dependencies was breaking in Wherobots runtimes. I think in general it is better for library maintainers to pin their dependencies and update them explicitly if version constraints are preventing installation. That way we can install a specific library version and know that it will install pinned upstream dependencies. 

The alternative is lots of wading through library release history trying to figure out what upstream dependencies used to be installed by leafmap.

**Comment by giswqs** [comment]
@rbavery Thank you for the heads up. Do you know which leafmap dependency is breaking the Wherobots runtimes? We can try to pin certain dependencies so that leafmap is compatible with both Wherobots and py.cafe.

**Comment by rbavery** [comment]
I don't, I recall I tried to track this down but because leafmap never pinned it was difficult and I set it aside. Instead I decided to wait a few release cycles and then give it another go with a future leafmap version that pinned dependencies.

**Comment by maartenbreddels** [comment]
I think libraries have to be conservative with pinning, since they need to be installable in many environments which may have many other version constraints (sometimes for good reasons). Application can use aggressive pinning, i have no problem with that.

Only if a particular library is incompatible should pinning be used. So I think it should be the inverse of what you say @rbavery.
If we start pinning aggressively, not even uv will be able to solve an environment with a few libraries in it, because the constraints are simply incompatible.



> The alternative is lots of wading through library release history trying to figure out what upstream dependencies used to be installed by leafmap.

I'm afraid that, or by trial and error (uv is super fast now, so experimenting is cheap) is the solution.
